name: web_driver_installer
description: For downloading/installing different web drivers. Used in tests.

environment:
  sdk: ">=2.2.2 <3.0.0"

dev_dependencies:
  args: 1.5.2
  http: ^0.12.0
  path: 1.6.4
  test: ^1.6.5
  yaml: 2.2.0
